# -*- coding: utf-8 -*-
"""TARGOL_WEEK_9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kNFHsy_F7tTR8W3cK6MfnJbZ7ruAGmZn
"""

import google.generativeai as genai

genai.configure(api_key="AIzaSyDI9Eqpok4NrUvBxT2yJ8LOseTF-gBJklY")
import google.generativeai as genai

genai.configure(api_key="AIzaSyDI9Eqpok4NrUvBxT2yJ8LOseTF-gBJklY")
model = genai.GenerativeModel(model_name="models/gemini-2.0-flash")
chat = model.start_chat(history=[])
import ipywidgets as widgets
from IPython.display import display, clear_output

input_box = widgets.Text(placeholder='Ask the chatbot anything...')
send_button = widgets.Button(description="Send", button_style='info')
output_area = widgets.Output()

def on_send_click(b):
    with output_area:
        clear_output()
        user_input = input_box.value
        print("You:", user_input)
        try:
            response = chat.send_message(user_input)
            print("Gemini:", response.text)
        except Exception as e:
            print("❌ Error:", str(e))

send_button.on_click(on_send_click)

display(widgets.VBox([input_box, send_button, output_area]))

!pip install google-generativeai --upgrade